import "server-only";
import type { Attack } from "./types";

/**
 * The 10 attack scripts, transcribed verbatim (names/narration) from the
 * reference `debrief.js` (`attacks` array, lines 70-379). Guarded with
 * `server-only` so an accidental client-component import fails the build
 * rather than leaking future-round narration to players.
 *
 * Two steps below (DoSing Kiddie step 1, Hacking Kiddie step 1) have empty
 * `counters` maps by design: they represent an attack that hasn't started
 * yet in round 1. `engine.server.ts` treats a step with no counters as
 * automatically countered with a "hasn't started yet" narrative, exactly
 * mirroring `debrief.js`'s `counter_attacks`/`render` behavior.
 *
 * "Nation State Disruption"'s steps 2-4 counter on the literal defence name
 * "None", which does not exist in the defence catalog — those steps can
 * only ever be countered via the "once countered, always countered"
 * propagation from step 1 (CCTV plant), never directly. This is preserved
 * verbatim from the source.
 */
export const ATTACKS: readonly Attack[] = [
  {
    name: "Scanning Kiddie",
    tier: "script_kiddie",
    steps: [
      {
        name: "Scan offices",
        effect: "No visible effect.",
        counters: {
          "Firewall office":
            "The office firewall intercepts a number of scanning attempts from all over the world. Apparently, there are people out there very interested in knowing more about your office network.",
        },
      },
      {
        name: "Scan offices",
        effect: "No visible effect.",
        counters: {
          "Firewall office":
            "The office firewall intercepts a number of scanning attempts from all over the world. Apparently, there are people out there very interested in knowing more about your office network.",
        },
      },
      {
        name: "Scan offices",
        effect: "No visible effect.",
        counters: {
          "Firewall office":
            "The office firewall intercepts a number of scanning attempts from all over the world. Apparently, there are people out there very interested in knowing more about your office network.",
        },
      },
      {
        name: "Scan offices",
        effect: "No visible effect.",
        counters: {
          "Firewall office":
            "The office firewall intercepts a number of scanning attempts from all over the world. Apparently, there are people out there very interested in knowing more about your office network.",
        },
      },
    ],
  },
  {
    name: "DoSing Kiddie",
    tier: "script_kiddie",
    steps: [
      {
        name: "",
        effect: "",
        counters: {},
      },
      {
        name: "DoS offices",
        effect:
          "The office network is hit with traffic generated by hundreds of infected bots from all around the world. The network is out of order, no one can connect to the Internet, and the local database and server crash. As no employee can work properly for several days, the share price takes a small dip.",
        counters: {
          "Firewall office":
            "A sudden surge of traffic is detected: a number of machines from all around the world are trying to flood your office network with requests. Fortunately, your network administrator can quickly update the filtering rules of the offices firewall, and the attack does not cause much disruption.",
        },
      },
      {
        name: "DoS offices",
        effect:
          "The office network is hit with traffic generated by hundreds of infected bots from all around the world. The network is out of order, no one can connect to the Internet, and the local database and server crash. As no employee can work properly for several days, the share price takes a small dip.",
        counters: {
          "Firewall office":
            "A sudden surge of traffic is detected: a number of machines from all around the world are trying to flood your office network with requests. Fortunately, your network administrator can quickly update the filtering rules of the offices firewall, and the attack does not cause much disruption.",
        },
      },
      {
        name: "DoS offices",
        effect:
          "The office network is hit with traffic generated by hundreds of infected bots from all around the world. The network is out of order, no one can connect to the Internet, and the local database and server crash. As no employee can work properly for several days, the share price takes a small dip.",
        counters: {
          "Firewall office":
            "A sudden surge of traffic is detected: a number of machines from all around the world are trying to flood your office network with requests. Fortunately, your network administrator can quickly update the filtering rules of the offices firewall, and the attack does not cause much disruption.",
        },
      },
    ],
  },
  {
    name: "Hacking Kiddie",
    tier: "script_kiddie",
    steps: [
      {
        name: "",
        effect: "",
        counters: {},
      },
      {
        name: "Remote control server offices",
        effect: "No visible effect.",
        counters: {
          "Upgrade server & DB":
            "The logs of the server show that someone on the Internet tried to use an SQL injection to compromise the server. This would have affected the old version of the software, but fortunately, the vulnerability has been patched.",
        },
      },
      {
        name: "Data exfiltration server offices",
        effect:
          "You receive a snarky email written in an approximate language and taunting the company for their poor security. Soon after, the company's email database is published on the Internet, and the press learns about the breach. The company's share price takes a small dip.",
        counters: {
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
          "Encryption DB":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
      {
        name: "Data exfiltration server offices",
        effect:
          "You receive a snarky email written in an approximate language and taunting the company for their poor security. Soon after, the company's email database is published on the Internet, and the press learns about the breach. The company's share price takes a small dip.",
        counters: {
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
          "Encryption DB":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
    ],
  },
  {
    name: "Phishing Kiddie",
    tier: "script_kiddie",
    steps: [
      {
        name: "Phishing offices (trojan)",
        effect: "No visible effect.",
        counters: {
          "Security training":
            "Upon receiving an email with an attachment from an unknown source, an employee reports it directly to you. Upon close inspection, the attachment did indeed contain malware. Good thing the employee knew better than opening it themselves!",
          Antivirus:
            "Upon opening an attachment from an unknown sender, the antivirus fires an alert and announces that a malicious program has been stopped from running on the computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Upgrade PC":
            "No visible effect: the upgrade makes PCs immune to the attack.",
        },
      },
      {
        name: "Disruption PC offices",
        effect:
          "Employees signal that their machines have stopped functioning and display bizarre messages. You receive a threatening email asking for a 10k ransom in exchange of a decryption key. The board of directors strictly forbids you from paying the ransom. The lost data is never recovered, and the infected machines have to be replaced. The company's share price suffers lightly from the disruption.",
        counters: {
          "Security training":
            "Upon receiving an email with an attachment from an unknown source, an employee reports it directly to you. Upon close inspection, the attachment did indeed contain malware. Good thing the employee knew better than opening it themselves!",
          Antivirus:
            "Upon opening an attachment from an unknown sender, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Upgrade PC":
            "No visible effect: the upgrade makes PCs immune to the attack.",
        },
      },
      {
        name: "Disruption PC offices",
        effect:
          "Employees signal that their machines have stopped functioning and display bizarre messages. You receive a threatening email asking for a 10k ransom in exchange of a decryption key. The board of directors strictly forbids you from paying the ransom. The lost data is never recovered, and the infected machines have to be replaced. The company's share price suffers lightly from the disruption.",
        counters: {
          "Security training":
            "Upon receiving an email with an attachment from an unknown source, an employee reports it directly to you. Upon close inspection, the attachment did indeed contain malware. Good thing the employee knew better than opening it themselves!",
          Antivirus:
            "Upon opening an attachment from an unknown sender, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Upgrade PC":
            "No visible effect: the upgrade makes PCs immune to the attack.",
        },
      },
      {
        name: "Disruption PC offices",
        effect:
          "Employees signal that their machines have stopped functioning and display bizarre messages. You receive a threatening email asking for a 10k ransom in exchange of a decryption key. The board of directors strictly forbids you from paying the ransom. The lost data is never recovered, and the infected machines have to be replaced. The company's share price suffers lightly from the disruption.",
        counters: {
          "Security training":
            "Upon receiving an email with an attachment from an unknown source, an employee reports it directly to you. Upon close inspection, the attachment did indeed contain malware. Good thing the employee knew better than opening it themselves!",
          Antivirus:
            "Upon opening an attachment from an unknown sender, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Upgrade PC":
            "No visible effect: the upgrade makes PCs immune to the attack.",
        },
      },
    ],
  },
  {
    name: "Mafia APT PC Offices",
    tier: "organised_crime",
    steps: [
      {
        name: "Infected USB offices",
        effect: "No visible effect.",
        counters: {
          "Security training":
            "Upon finding a thumb drive in the office's parking lot, an employee reports it directly to you. Upon close inspection, the thumb drive did indeed contain malware. Good thing the employee knew better than opening it themselves!",
          Antivirus:
            "Upon plugging in a thumb drive found in the office's parking lot, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
        },
      },
      {
        name: "Remote Control PC offices",
        effect: "No visible effect.",
        counters: {
          Antivirus:
            "One day, seemingly out of nowhere, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected suspicious activity on the office network. A PC seems to be communicating at regular intervals with an unknown machine on the Internet, located in a foreign country. Upon closer investigation, the PC was compromised and remotely operated: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
        },
      },
      {
        name: "Data exfiltration PC offices",
        effect:
          "A data dump is advertised for sale on the Dark Web, that contains sensitive emails and technical data from the company. The press learns about the data leak, and the company's share price plummets.",
        counters: {
          Antivirus:
            "One day, seemingly out of nowhere, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from a PC and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
          "Encryption PC":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
      {
        name: "Data exfiltration PC offices",
        effect:
          "A new data dump is leaked with ever more sensitive content, as well as non-important yet embarrassing personal email. You are forced to shut down the entire infrastructure for sanitisation. The company's share price crashes.",
        counters: {
          Antivirus:
            "One day, seemingly out of nowhere, the antivirus fires an alert and announces that a malicious program has been stopped from running on an office computer. Upon closer inspection, it was indeed a common piece of malware the antivirus stopped just in time: disaster averted!",
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from a PC and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
          "Encryption PC":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
    ],
  },
  {
    name: "Mafia APT Server Offices",
    tier: "organised_crime",
    steps: [
      {
        name: "Phishing offices (credentials)",
        effect: "No visible effect.",
        counters: {
          "Security training":
            "Upon receiving an email with an attachment from an unknown source, your server administrator reports it directly to you. Upon close inspection, the attachment did indeed contain malware. Good thing they knew better than opening it themselves!",
        },
      },
      {
        name: "Remote Control Server offices",
        effect: "No visible effect.",
        counters: {
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected suspicious activity on the office network. The server seems to be communicating at regular intervals with an unknown machine on the Internet, located in a foreign country. Upon closer investigation, the server was compromised and remotely operated: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
        },
      },
      {
        name: "Data exfiltration DB offices",
        effect:
          "A data dump is put on sale on the Dark Web containing sensitive data from the company: email, HR records, client contracts, and banking details. The press learns about the data leak and the company's share price plummets",
        counters: {
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the office database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
          "Encryption DB":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
      {
        name: "Data exfiltration DB offices",
        effect:
          "A cryptolocker locks down the content of the office database. As all activity has to be stopped in the office, since no one can work without access to the database, you receive a chilling email asking for a 500k ransom. The board of directors refuses to pay any ransom, and the company, having lost one of its core assets, is forced to shut down.",
        counters: {
          "Monitoring office":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the office database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected target is removed.",
          "Encryption DB":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
    ],
  },
  {
    name: "Mafia APT Server Plant",
    tier: "organised_crime",
    steps: [
      {
        name: "Vulnerable Wi-Fi plant",
        effect: "No visible effect.",
        counters: {
          "Asset audit":
            "During the asset audit, an unsecured, undocumented Wi-Fi network was found in the plant. After some investigation, this was set up years ago by an engineer, who is now retired. They needed to install a set of additional debit sensors on the water stream, and an open Wi-Fi network was a cheap and simple solution compared to deploying a complicated set of cables. The Wi-Fi network was never documented and eventually forgotten. It has now been secured with a strong password.",
        },
      },
      {
        name: "Remote Control DB plant",
        effect: "No visible effect.",
        counters: {
          "Monitoring plant":
            "One day, the office's network administrator comes to talk to you: they have detected suspicious activity on the plant network. The historian database seems to be communicating at regular intervals with an unknown machine on the Internet, located in a foreign country. Upon closer investigation, the historian was compromised and remotely operated: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the historian is removed.",
          "Upgrade server & DB":
            "No visible effect: the upgrade makes the database immune to the attack.",
        },
      },
      {
        name: "Data exfiltration DB plant",
        effect:
          "One of your competitors alerts you that someone is trying to sell sensitive data apparently stolen from your plant database. Shortly after, the story leaks to the press. The company's share price plummets.",
        counters: {
          "Monitoring plant":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the historian database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected historian is removed.",
          "Encryption DB":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
      {
        name: "Data exfiltration DB plant",
        effect:
          "One day, the plant database crashes, and recovery attempts reveal that the entire contents have been corrupted. All activities slow down significantly for a few days, as the company's share price takes another dive.",
        counters: {
          "Monitoring plant":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the historian database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected historian is removed.",
          "Encryption DB":
            "No visible effect: the data stolen by the attackers is unreadable and cannot be exploited.",
        },
      },
    ],
  },
  {
    name: "Mafia Disruption Controller",
    tier: "organised_crime",
    steps: [
      {
        name: "Scan plant",
        effect: "No visible effect.",
        counters: {
          "Firewall plant":
            "The firewall intercepts a number of scanning attempts from all over the world. Apparently, there are people out there very interested in knowing more about your plant.",
        },
      },
      {
        name: "Remote control Controller",
        effect: "No visible effect.",
        counters: {
          "Upgrade controller":
            "No visible effect: the upgrade makes the controller immune to the attack.",
          "Firewall plant":
            "Upon looking at detailed firewall logs, your plant network administrator discovers that an overseas machine tried to query the remote administration port of your SCADA controller. Fortunately, the firewall's rules denied access to the attacker.",
        },
      },
      {
        name: "Disruption controller",
        effect:
          "One day, the turbines suffer from a partial failure, and the damage requires several days of maintenance. Shortly after, you receive a message claiming responsibility for hacking the turbine's controller, and asking for a 500k ransom. The board of directors forbids you from paying anything. The company's share price plummets.",
        counters: {
          "Upgrade controller":
            "No visible effect: the upgrade makes the controller immune to the attack.",
        },
      },
      {
        name: "Disruption controller",
        effect:
          "One day, the turbines start accelerating out of control and finally blow up. Several employees are injured. The company, having lost one of its core assets, is forced to shut down.",
        counters: {
          "Upgrade controller":
            "No visible effect: the upgrade makes the controller immune to the attack.",
        },
      },
    ],
  },
  {
    name: "Nation State Intelligence",
    tier: "nation_state",
    steps: [
      {
        name: "Physical intrusion plant",
        effect: "No visible effect.",
        counters: {
          "CCTV plant":
            "An intruder is detected entering the plant perimeter and trying to access the buildings. The moment the security guard comes and asks them what they are doing, they run away.",
        },
      },
      {
        name: "Remote control DB plant (0day)",
        effect: "No visible effect.",
        counters: {
          "Monitoring plant":
            "One day, the office's network administrator comes to talk to you: they have detected suspicious activity on the plant network. The historian database seems to be communicating at regular intervals with an unknown machine on the Internet, located in a foreign country. Upon closer investigation, the historian was compromised and remotely operated: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the historian is removed.",
        },
      },
      {
        name: "Data exfiltration DB plant",
        effect: "No visible effect.",
        counters: {
          "Monitoring plant":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the historian database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected historian is removed.",
        },
      },
      {
        name: "Data exfiltration DB plant",
        effect:
          "Optional description: You get a visit from the secret services, telling you that sensitive data related to the company was stolen by a foreign country. The data comes apparently from your plant database, which was compromised for months after a very sophisticated infiltration by foreign agents. Luckily, the public does not learn about it.",
        counters: {
          "Monitoring plant":
            "One day, the office's network administrator comes to talk to you: they have detected a suspicious data stream originating from the historian database and going to an unknown address on the Internet, located in a foreign country. Upon closer investigation, it was a data exfiltration attack: the administrator makes sure that the link to the attacker's machine is shut down and any malware on the infected historian is removed.",
        },
      },
    ],
  },
  {
    // See note above about the "None" counter: this attack is only
    // stoppable via earlier-counter propagation from step 1 (CCTV plant).
    name: "Nation State Disruption",
    tier: "nation_state",
    steps: [
      {
        name: "Physical intrusion plant",
        effect: "No visible effect.",
        counters: {
          "CCTV plant":
            "An intruder is detected entering the plant perimeter and trying to access the buildings. The moment the security guard comes and asks them what they are doing, they run away.",
        },
      },
      {
        name: "Remote control controller (0day)",
        effect: "No visible effect.",
        counters: { None: "" },
      },
      {
        name: "Remote control controller (0day)",
        effect: "No visible effect.",
        counters: { None: "" },
      },
      {
        name: "Disruption controller",
        effect:
          "Optional description: one day, the turbines start accelerating out of control and finally blow up. Several employees are injured. The company, having lost one of its core assets, is forced to shut down.",
        counters: { None: "" },
      },
    ],
  },
] as const;
